librenms:
  extraEnvs:
    - name: GLOBAL_DEBUG
      value: "true"
  initContainer:
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 100Mi
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 50Mi
  snmp_scanner:
    enabled: true
    extraEnvs:
      - name: SCAN_DEBUG
        value: "true"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 200Mi
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 100Mi
  frontend:
    extraEnvs:
      - name: FRONTEND_DEBUG
        value: "true"
    extraVolumeMounts:
      - name: files
        mountPath: /data/extra/frontend.txt
        subPath: custom.php
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
        ephemeral-storage: 500Mi
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 250Mi
  poller:
    extraEnvs:
      - name: POLLER_DEBUG
        value: "true"
    extraVolumeMounts:
      - name: files
        mountPath: /data/extra/poller.txt
        subPath: custom.php
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
        ephemeral-storage: 500Mi
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 250Mi
  rrdcached:
    extraEnvs:
      - name: RRD_DEBUG
        value: "true"
    extraVolumeMounts:
      - name: db
        mountPath: /data/extra-db
        subPath: extra
      - name: journal
        mountPath: /data/extra-journal
        subPath: extra
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 500Mi
ingress:
  enabled: true
