{{- if .Values.librenms.frontend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-frontend-data
  labels:
    app.kubernetes.io/name: {{ include "librenms.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.librenms.frontend.persistence.size }}
  {{- if .Values.librenms.frontend.persistence.storageClassName }}
  storageClassName: {{ .Values.librenms.frontend.persistence.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}
